# Heavy-Tailed Distributions {.evt}

## Heavy-tailed distributions

<!--
Intro to heavy-tailed and subexponential
1장
-->

::: {#def-taifct}

- **Tail function** $\overline{F}$ of a distribution $F$ on $\mathbb{R}$ to be given by $\overline{F}(x) = F(x,\infty), \forall x$.

- **Tail property** of $F$: any property which depends only on $\{ \overline{F} (x) : x \geq x_0 \}$ for any (finite) $x_0$.

- We say that $F$ has **right-unbounded support** if $\overline{F}(x) >0, \forall x$.

:::

::: {#def-heavytaileddist}

## Heavy-tailed distributions

- A distribution $F$ on $\mathbb{R}$ is said to be **right heavy-tailed** if
$$
\int_{-\infty}^{\infty}e^{\lambda x} F(dx) = \infty, \quad{} \forall \lambda >0,
$$
that is, iff $F$ fails to posses any positive exponential moment.

- Otherwise $F$ is said to be **light-tailed**.

:::

::: {#def-longtaileddist}

## Long-tailed distributions

- A distribution $F$ on $\mathbb{R}$ is said to be **long-tailed** if $F$ has right-unbounded support and, for any fixed $y>0$,
$$
\frac{\overline{F}(x+y)}{\overline{F}(x)} \rightarrow 1, \quad{} \text{as } x \rightarrow \infty.
$$

:::

::: callout-tip
## Remark

- Clearly to be long-tailed is again a tail property of a distribution. 

- Further, it is fairly easy to see that a long-tailed distribution is also heavy-tailed. 

:::

::: {#def-longtaileddist}

## Subexponential distributions

- A distribution $F$ on $\mathbb{R}^{+}$ is said to be **subexponential** if
$$
\lim_{x\rightarrow\infty}\frac{\overline{F * F}(x)}{\overline{F}(x)}=2.
$$

:::

## Examples of heavy-tailed distributions