# Measure and Integration {#sec-measure}

## Limit of sets

<!--
https://math.iisc.ac.in/~manju/PT2019/Lectures-part1.pdf
-->

우리는 $\sigma$-field 에만 관심을 갖고 있지만 이를 설명하는 데 유용한 더 작은 하위 클래스들이 있다.

::: {#def-algebra}

- $S$: a collection of subsets of $\Omega$. We say that $S$ is a

1. $\pi$-**system**: if $A, B \in S \Longrightarrow A\cap B \in S$

2. $\lambda$-**system**: if
    + $\Omega \in S$
    + $A, B \in S$ and $A \subseteq B \Longrightarrow B \backslash A \in S$
    + $A_n \uparrow A$ and $A_n \in S \Longrightarrow A \in S$
    
3. **Algebra** (field) if
    + $\emptyset , \Omega \in S$
    + $A \in S \Longrightarrow A^c \in S$
    + $A, B \in S \Longrightarrow A\cup B \in S$

4. **Monotone class** if
    + $A_n \in S$ and $A_n \uparrow A \Longrightarrow A \in S$
    + $A_n \in S$ and $A_n \downarrow A \Longrightarrow A \in S$
    + Recall that $A_n \uparrow A$ means that $A_1 \subseteq A_2 \subseteq \ldots$ and $\cup_n A_n = A$ and $A_n \downarrow A$ means that $A_n \supseteq A_2 \supseteq \ldots$ and $\cap_n A_n = A$
    
5. $\sigma$-**algebra** (field) if
    + $\emptyset, \Omega \in S$
    + $A \in S \Longrightarrow A^c \in S$
    + $A_n \in S \Longrightarrow \cup A_n \in S$

:::

::: callout-tip
## Remark

- $\sigma$-algebra는 $\pi$-system, $\lambda$-system, monotone class 그리고 algebra이다.

- Arbitrary intersections of $\sigma$-algebra, algebra, $\pi$-system, $\lambda$-system은 각각 $\sigma$-algebra, algebra, $\pi$-system, $\lambda$-system이다.

:::

다음은 [PROBABILITY THEORY - PART 1 MEASURE THEORETICAL FRAMEWORK](https://math.iisc.ac.in/~manju/PT2019/Lectures-part1.pdf) 에서 가져온 몇 가지 예이다.

| $\Omega$ | $S(\pi$-system) | $\mathcal{A}(S)$ (algebra generated by $S$) | $\sigma(S)$ |
|:---:|:---:|:---:|:---:|
| $(0,1]$ | $\{(a,b]: 0<a\leq b \leq 1\}$ | $\{ \cup_{k=1}^N I_k: I_k \in S \text{ are pairwise disjoint}\}$ | $\mathcal{B}(0,1]$ |
| $[0,1]$ | $\{(a,b]\cap [0,1]: a \leq b\}$ | $\{\cup_{k=1}^N R_k: R_k \in S \text{ are pairwise disjoint}\}$ | $\mathcal{B}[0,1]$ |
| $\mathbb{R}^d$ | $\{\prod_{i=1}^d (a_i, b_i]: a_i \leq b_i\}$ | $\{\cup_{k=1}^N R_k: R_k \in S \text{ are pairwise disjoint}\}$ | $\mathcal{B}_{\mathbb{R}^d}$ |
| $\{0,1\}^{\mathbb{N}}$ | Collection of all cylinder sets | Finite disjoint unions of cylinders | $\mathcal{B}(\{0,1\}^{\mathbb{N}})$ |

위 표를 보면, $\pi$-system이나 이  $\pi$-system으로 만든 algebra는 명시적으로 표사되어 있으나, $\sigma$-algebra를 이해하기는 쉽지 않다. 이는 Borel set은 countable number of operations on intervals로 표현하기 쉽지 않기 때문이라고 한다.

이렇게 원소를 파악하기 어려운 $\sigma$-algebra에 대해 말해주는 보조정리 뒤 개가 있다. 이들이 말하고자 하는 바는 동일하고 많은 경우에 둘을 바꿔서 사용할 수 있다고 한다.

::: {#lem-pilambdathm}

## $\pi-\lambda$ theorem

- Let $\Omega$ be a set and $\mathcal{F}$ be a set of subsets of $\Omega$.

1. $\mathcal{F}$ is a $\sigma$-algebra $\Longleftrightarrow$ it is a $\pi$-system as well as a $\lambda$-system.

2. If $S$ is a $\pi$-system, then $\lambda (S) = \sigma(S)$. 이때  $\lambda (S)$는 $S$를 포함하는 모든 $\lambda$-system들의 intersection이다.

:::

::: {.callout-note collapse="true"}
## Proof

1. 한쪽 방향은 분명하다. $\mathcal{F}$가 $\pi$-system이면서 $\lambda$-system이라고 하자. 그러면 $\Omega \in \mathcal{F}$이고 만약 $A\in \mathcal{F}$이면, $A^c = \Omega \backslash A \in \mathcal{F}$이다. 만약 $A_n \in \mathcal{F}$이면, 이것의 finite unions $B_n := \cup_{k=1}^n A_k = (\cap_{k=1}^n A_k^c)^c \in \mathcal{F}$이다. (intersection에서는 $\mathcal{F}$가 $\pi$-system이라는 것을 이용) 또한 countable union $\cup A_n$ 또한 $B_n$의 increasing limit이고 $\mathcal{F}$ 안에 들어가기에 $\lambda$-property를 만족

2. $\lambda (S)$ 자체도 $S$를 포함하는 가장 작은 $\lambda$-system이다. 이에 $\lambda (S) = \sigma (S)$를 보이려면 $\mathcal{F}:=\lambda (S)$가 $\pi$-system임을 보이면 된다. 즉 $A, B \in \mathcal{F}$이면 $A\cap B \in \mathcal{F}$임을 보이면 된다. $A\in S$를 고정하고 $\mathcal{F}_A := \{ B \in \mathcal{F}: B \cap A \in \mathcal{F}\}$라 하자. $S$가 $\pi$-system이므로 $\mathcal{F}_A \supset S$이다. 여기서 $\mathcal{F}_A$가 $\lambda$-system임을 보이고자 한다. $\Omega \in \mathcal{F}_A$이다. 만약 $B, C \in \mathcal{F}_A$이고 $B\subseteq C$이면, $\mathcal{F}$가 $C\cap A$와 $B\cap A$를 포함하는 $\lambda$-system이기 때문에 $(C\backslash B) \cap A = (C \cap A) \backslash (B \cap A) \in \mathcal{F}$이다. 따라서 $(C\backslash B) \in \mathcal{F}_A$이다. 마지막으로 만약 $B_n \in \mathcal{F}_A$이고 $B_n \uparrow B$이면, $B_n \cap A \in \mathcal{F}_A$이고 $B_n \cap A \uparrow B \cap A$이다. 따라서 $B \in \mathcal{F}_A$이다. 이것은 $\mathcal{F}_A$가 $S$를 포함하는 $\lambda$-system임을 의미하며 따라서 $\mathcal{F}_A \supset \mathcal{F}$이다. 다른 말로, 모든 $A \in S$와 $B \in \mathcal{F}$에 대해 $A \cap B \in \mathcal{F}$이다. 이제 $A\in\mathcal{F}$를 고정하자. 다시 $\mathcal{F}_A := \{ B\in \mathcal{F}: B\cap A \in \mathcal{F}\}$라고 정의하자. 앞에서 보인대로 하면 $\mathcal{F}_A \supset S$임을 보일 수 있다. 이를 바탕으로 $\mathcal{F}_A$가 $\lambda$-system이며 모든 $A \in \mathcal{F}$에서 $\mathcal{F}_A = \mathcal{F}$임을 보일 수 있다. 즉 $\mathcal{F}$는 $\pi$-system이다.

:::

::: {#lem-monotoneclassthm}

## Monotone class theorem

- Let $\Omega$ be a set and let $S$ be a collection of $\Omega$. If $S$ is an algebra, then the monotone class generated by $S$ is a $\sigma$-algebra. That is, $\mathcal{M}(S) = \sigma(S)$.

:::

**Q**. (Unique extension of measures) $(\mathbb{R}, \mathcal{B})$에서의 두 확률측도가 모든 구간에서 일치한다면, 이들은 같은가?

다음 예를 통해 거짓이라는 것을 확인할 수 있다.

<!--
https://math.iisc.ac.in/~manju/PT2019/Lectures-part1.pdf
-->

::: {#exm-differentprobmeasures}

## $\pi-\lambda$ theorem

- $\Omega = \{1,2,3,4\}$이고 $S = \{\{1,2\},\{2,3\},\{3,4\}\}$라고 하자. 그러면 $\sigma (S) = 2^{\Omega}$ (power set)이라는 것을 보일 수 있다. 

- $\Omega$에서 두 확률측도 $\mu, \nu$를 각각
    + $\mu_i = \frac{1}{4}, \forall i$
    + $\nu_1 = \nu_3 =\frac{1}{2}$, $\nu_2 = \nu_4 = 0$
이라고 하자. 그러면 $\mu(A)=\frac{1}{2}=\nu (A)$ for all $A \in S$이나, $\mu \neq \nu$ on $\sigma (S)$이다.

:::

다만 다음 따름정리와 같이 긍정적인 결과도 있다.

::: {#lem-pisysequivprob}

$S$가 $\Omega$의 부분집합의 $\pi$-system이고 $\mathcal{F} = \sigma (S)$라 하자. 만약 $\mathbb{P} = \mathbb{Q}$가 $\mathcal{F}$에서의 확률측도이며 모든 $A \in S$에서 $\mathbb{P}(A) =\mathbb{Q}(A)$라 하자. 그러면 모든 $A\in \mathcal{F}$에서 $\mathbb{P}(A) =\mathbb{Q}(A)$이다.

:::

::: {.callout-note collapse="true"}
## Proof

- $\mathcal{G} =\{A \in \mathcal{F}: \mathbb{P}(A) = \mathbb{Q}(A)\}$라 하자. 가정에 의해 $\mathcal{G} \supseteq S$이다. 

- 여기서 $\mathcal{G}$가 $\lambda$-system임을 밝히고자 한다. 분명히 $\Omega \in \mathcal{G}$이;다. 만약 $A, B \in \mathcal{G}$이고 $A \supseteq B$이면, $\mathbb{P}(A\backslash B) = \mathbb{P}(A) - \mathbb{P}(B) = \mathbb{Q}(A) - \mathbb{Q}(B) = \mathbb{Q}(A\backslash B)$이다. 이는 즉 $A \backslash B \in \mathcal{G}$임을 내포한다. 마지막으로 만약 $A_n \in \mathcal{G}$이고 $A_n \uparrow A$이면, $\mathbb{P}(A) = \lim_{n\rightarrow \infty} \mathbb{P}(A_n) = \lim_{n\rightarrow \infty}\mathbb{Q}(A_n) = \mathbb{Q}(A)$이다. (이는 measure의 countable additivity로부터 옴) 

- 따라서 $\mathcal{G} \supseteq \lambda (S)$이고 이는 @lem-pilambdathm 에 의해 $\sigma (S)$와 같음을 보일 수 있다. 따라서 $\mathcal{F}$에서 $\mathbb{P}= \mathbb{Q}$이다.

:::

다시 @exm-differentprobmeasures 를 살펴보면, $S$가 $\pi$-system이 아니라는 것을 알 수 있다.

::: callout-tip
## Remark

- $\sigma$-algebra의 집합, 특히 Borel 집합은 항상 어떤 interval의 가산 합집합이 아니기 때문에, $\sigma$-algebra의  모든 요소에 대해 어떤 성질이 성립함을 보이기 위해, 우리는 그 성질을 가진 모든 집합의 collection을 고려하고, 이 collection이 $\sigma$-algebra임을 보여준다. 이 과정에서 그것이 $\lambda$-system이거나 monotone class ($\pi$-system과 algebra를 포함하는) 임을 보여주는 것이 더 쉬울 수 있다.

:::

## Measures

```{=html}
<!--
오슬로 확률론 강의노트 3.2
Probability, Measure, and Martingales 강의노트
https://courses.maths.ox.ac.uk/pluginfile.php/25901/mod_resource/content/7/Martingales2022.pdf
-->
```

::: {#def-sigmaadditive}

## $\sigma$-additive

- $\mathcal{A}$: a collection of subsets of $\Omega$ containing the empty set $\emptyset$

- A **set function** on $\mathcal{A}$: $\mu : \mathcal{A} \rightarrow [0,\infty]$ with $\mu (\emptyset) = 0$

- We say that $\mu$ is **countably additive**, or $\sigma$-**additive**, if for all sequences $(A_n)$ of disjoint sets in $\mathcal{A}$ with $\cup_{n=1}^{\infty}A_n \in \mathcal{A}$
$$
\mu \Big( \bigcup_{n=1}^{\infty} A_n \Big) = \sum_{n=1}^{\infty}\mu (A_n).
$$

:::

::: callout-tip
## Remark

- Recall that a **measurable space** is a pair $(\Omega, \mathcal{F})$, where $\mathcal{F}$ is a $\sigma$-algebra on $\Omega$.

:::

::: {#def-measurespace}

## Measure space

- A **measure space** is a triple $(\Omega, \mathcal{F}, \mu)$, where
    + $\Omega$: set
    + $\mathcal{F}$: $\sigma$-algebra on $\Omega$
    + $\mu$: $\mathcal{F} \rightarrow [0,\infty]$ is a countably additive set function.
    + Then $\mu$ is a measure on $(\Omega, \mathcal{F})$.

:::

<!--
https://courses.maths.ox.ac.uk/pluginfile.php/25901/mod_resource/content/7/Martingales2022.pdf
-->

이산 측도를 생각하는 것은 그냥 power set에서 생각하면 되기에 쉽다. 그러나 일반적인 상황에서는 $\Omega$의 모든 subset을 잴 수 있는 measure를 정의할 수 없다. 그래서 "충분히 큰" collection of sets에서 정의되는 측도의 존재를 보이는 것은 쉽지 않다. 한 가지 방법으로 $\Omega$의 smaller class of subsets에서의 측도를 만들고 $\sigma$-algebra를 generate하는 방법이 있다. 이를 위해 두 가지 문제를 해결해야 한다.

1. (Construction) 우리가 특정한 measure를 whole $\sigma$-algebra에 확장할 수 있을까? (**Caratheodory’s Extension Theorem**)

2. (Uniqueness) $\sigma$-algebra에서 우리가 만들고자 하는 측도가 단 한개만 존재하는가? ($\pi-\lambda$ **systems Lemma**)


### Lebesgue measure

<!--
https://math.iisc.ac.in/~manju/PT2019/Lectures-part1.pdf
-->

::: {#def-existenceuniquenessLebesgue}

## Existence and uniqueness of Lebesgue measure

- There exists a unique Borel measure $\lambda$ on $[0,1]$ such that $\lambda (I) = \vert I \vert$ for any interval $I$.

:::

::: {.callout-note collapse="true"}
## Proof

- $S = \{ (a,b] \cap [0,1]\}$은 $\mathcal{B}$를 생성하는 $\pi$-system이다. 따라서 @lem-pisysequivprob 에 의해 uniqueness가 증명된다.

- Existence는 증명이 길고 복잡한데, 몇 가지 개요만을 아래에서 서술한다. 좀 더 자세한 사항은 [PROBABILITY THEORY - PART 1 MEASURE THEORETICAL FRAMEWORK](https://math.iisc.ac.in/~manju/PT2019/Lectures-part1.pdf) 를 보길 바란다. 여기서는 $\Omega = [0,1]$로 둔다.

:::

1. **Outer measure** $\lambda_{*}$를 정의한다.
$$
\lambda_{*}(A) = \inf \{ \sum \vert I_k \vert : \text{ each }I_k \text{ is an open interval and } \{I_k\} \text{ a countable cover for } A \}.
$$
참고로 outer measure의 성질은 다음과 같다.
    + 모든 subset $A\subseteq \Omega$에 대해 $0\leq \lambda_{*}(A) \leq 1$
    + $\lambda_{*}(A\cup B) \leq \lambda_{*}(A) + \lambda_{*}(B)$, for any $A, B \subseteq \Omega$
    + $\lambda_{*}(\Omega)=1$
    
2. $\lambda_{*}$가 측도가 되도록 하는 $\sigma$-field를 잡는다. $\lambda_{*}$를 a set $\Omega$에서의 outer measure라고 하자. Caratheodary의 정의에 의해
$$
\mathcal{F}:= \{ A\subseteq \Omega : \lambda_{*}(E) = \lambda_{*}(A\cap E) + \lambda_{*}(A^c \cap E) \text{ for any } E\}.
$$
이때 $\mathcal{F}$가 $\sigma$-algebra이고 $\lambda_{*}$ restricted to $\mathcal{F}$가 확률측도임을 보일 수 있다.

3. $A= (a,b]\subseteq [0,1]$일 때 $A\in \mathcal{F}$임을 보여 $\mathcal{F}$가 모든 보렐 집합을 포함함을 보인다. 즉 $\mathcal{F}$가 충분히 큼을 보인다.


### Construction of Lebesgue measure

<!--
https://math.iisc.ac.in/~manju/PT2019/Lectures-part1.pdf
-->

Lebesgue 측도의 구축은 충분히 풍부한 집합 class에서 시작하여 흥미로운 측도를 구성하는 일반적인 절차로 발전할 수 있다.

1. 주어진 algebra $\mathcal{A}$ (이 경우 유한 개의 $(a,b]$의 합집합)
와 $\mathcal{A}$ 위의 countably additive probability measure $P$ on $\mathcal{A}$에 대해, 모든 부분집합에 대해 outer measure $P^{*}$를 $\mathcal{A}$의 집합들로 구성된 countable cover에 대한 최솟값을 취함으로써 구성한다. 구체적으로, 임의의 부분집합 $E$에 대해
$$
P^{*}(E) = \inf \{\sum_{i=1}^{\infty} P(A_i): E \supseteq \cup_{i=1}^{\infty}A_i, A_i \in \mathcal{A} \}.
$$

2. $\mathcal{F}$를 위에서와 같이 정의하고, $\mathcal{F}\supset \mathcal{A}$가 $\sigma$-algebra이고 $P^{*}$가 $\mathcal{A}$에서의 확률측도임을 보인다.

3. $P^{*}=P$ on $\mathcal{A}$임을 보인다.

### Push-forward (image) measure

- Measure를 정의하는 방법
    + Caratheodory Extension Theorem
    + Transportation between spaces via functions.
    
::: {#def-pushforwardm}
## Push-forward measure

- $(\Omega, \mathcal{F}, \mathbb{P})$를 확률공간이라 하고, $X$를 $(\Omega, \mathcal{F})$에서 $(E, \mathcal{E})$로 보내는 확률변수라 하자.
그러면
$$
\mathbb{Q}(A) = \mathbb{P}(X^{-1}(A)), \quad{} A\in \mathcal{E}
$$
는 $(E,\mathcal{E})$에서 측도를 정의한다 (**push-forward measure**). 

- 이때 $\mathbb{Q} = \mathbb{P}\circ X^{-1}$이라고 쓰고 **law of the distribution** of $X$라고 부른다.

:::    

<!--
마지막 remark 출처
https://math.iisc.ac.in/~manju/PT2019/Lectures-part1.pdf
-->

::: callout-tip
## Remark

- 집합 $E$의 측도로 먼저 이를 $X^{-1}$을 이용해 $\Omega$로 보내고 $\mathbb{P}$를 이용해 잰다. 

-   Push-forward measure는 change-of-variables formula 등 적분이론에서 많이 쓰임

- $\mathbb{Q}$가 측도인 이유는 만약 $A_n$이 pairwise disjoint이면 $X^{-1}(A_n)$ 또한 pairwise disjoint이기 때문이다. 그러나 $B_n$이 $\Omega$에서 pairwise disjoint라고 해서, $X(B_n)$이 disjoint하지는 않다. 그래서 일반적으로 **pull-back measure**는 없다. 그러나 $X$가 일대일함수면 $X^{-1}$을 pull-back으로 생각할 수 있다.

:::
    
<!--    
::: {#def-pushforwardm}
## Push-forward measure

-   $(E,\mathcal{E},\mu)$: measure space, $(F, \mathcal{F})$: measurable space, $f: E\rightarrow F$: measurable transformation

-   그러면 다음과 같은 변환 $$
    \mu_f (A) \stackrel{\Delta}{=}\mu \circ f^{-1}(A) = \mu (f^{-1}(A)), \quad{} A\in \mathcal{F}
    $$ 은 $(F, \mathcal{F})$에서의 measure를 정의

-   $\mu_f$ (또는 $f^\#\mu$로 씀): **push-forward measure** via $f$
:::
-->


## Integration

### Integration notations

::: callout-tip
## Remark

적분이론에서 굉장히 다양한 적분 notation을 쓰는데 알아두면 좋을 듯
:::

```{=html}
<!--
오슬로 확률론 강의노트 3.2
-->
```
-   $(E,\mathcal{E},\mu)$: measure space, $f: E \rightarrow\mathbb{R}$: a real-valued transformation

-   다음의 세 개의 기호는 같은 것임

    -   $\int_E f(x) d\mu (x)$
    -   $\int_E f d\mu$ (적분하려는 변수가 분명한 경우 생략)
    -   $\int_E f(x) \mu (dx)$

### 리만-스틸체스 적분

종종 헷갈리는 표현이 기댓값을 다음과 같이 분포함수를 이용해 표현하는 경우가 있다.

$$
E(X) = \int x dF(x).
$$

우리가 알고 있는 정적분은 $x$축을 따라가며 함수값 f(x)가 만드는 면적을 계산한다.

$$
\int_a^b f(x) dx.
$$

위 식을 더 확장하면 $x$ 대신 임의의 곡선 $g(x)$를 적분 변수로 두고 $f(x)$ 를 단순하게 정적분 할 수도 있다.

$$
\int_{x=a}^b f(x) dg(x).
$$

여기서 $dg(x)$는 $g(x)$의 미분소(differential)로, $g(x)$의 움직임을 결정하는 $x$는 단조 증가하거나 감소한다. 위와 같이 리만 적분을 일반화한 정적분을 **리만-스틸체스 적분(Riemann-Stieltjes Integral)**이라 한다. 리만 적분의 정의를 이용해 리만-스틸체스의 적분을 표현할 수도 있다.

$$
\int_{x=a}^b f(x) dg(x) = \lim_{N\rightarrow \infty} \sum_{n=0}^{N-1} f(t_n) [g(x_{n+1}) - g(x_n)].
$$

여기서 $x_n$은 정적분을 위해 구간 $[a,b]$를 나눈 점, $t_n$은 닫힌 세부공간 $[x_n, x_{n+1} ]$사이에 있는 임의점이다.

::: {#exm-riemmanstieltjesint01}
## 리만-스틸체스 적분을 이용한 기댓값의 계산

```{=html}
<!--
https://www.statlect.com/fundamentals-of-probability/expected-value
-->
```
-   $X$: random variable with support $R_X = [0,1]$ and distribution function $$
    F_X(x) = \begin{cases}
    0, &\text{if } x <0\\
    \frac{1}{2}x, &\text{if } 0 \leq x < 1\\
    1, &\text{if } x \geq 1.
    \end{cases}
    $$

-   이때의 기댓값은 
    $$
    \begin{aligned}
    E[X] &= \int_{-\infty}^{\infty} x dF_X(x)\\
    &= \int_0^1 xdF_{X}(x) + 1\cdot \Big[ F_X(1) -\lim_{x\rightarrow 1, x < 1}F_X(x) \Big]\\
    &= \int_0^1 x \frac{d}{dx} \Big(\frac{1}{2}x \Big) dx  + 1 \cdot \Big[ 1- \frac{1}{2} \Big]\\
    &= \Big[\frac{1}{4}x^2 \Big]_{0}^1 + \frac{1}{2} = \frac{1}{4}+\frac{1}{2}=\frac{3}{4}.
    \end{aligned}
    $$
:::

## 리만 적분과 르베그 적분

여기는 [Confused when changing from Lebesgue Integral to Riemann Integral](https://math.stackexchange.com/questions/2958787/confused-when-changing-from-lebesgue-integral-to-riemann-integral) 에 올라왔던 내용을 살펴보기로 한다. 여기서 질문자는 리만 적분을 어떻게 르베그 적분으로 바꾸는지에 대해 관심이 있다.

다음과 같이 확률공간 $(\Omega, \mathcal{F}, P)$에서 정의된 음이 아닌 확률변수 $X$가 지수분포를 따른다고 하자. $$
P(X<x) = 1-e^{-\lambda x}.
$$ 한편, 르베그 적분으로 $X$의 기댓값을 쓰면 다음과 같다. $$
E[X] = \int_{\{\omega | X(\omega) \geq 0 \}} X(\omega) dP(\omega).
$$ 여기서 질문자는 이것을 리만 적분으로 어떻게 바꾸냐 $$
E[X] = \int_0^\infty x \lambda e^{-\lambda x}dx
$$ 를 물어보고 있다.

답변은 이것이 적분의 문제가 아닌 변수변환의 문제라고 한다.

By definition, given $X: \Omega \rightarrow \mathbb{R}$ a random variable, $E[X] = \int_{\Omega} X$. $X$ defines a measure $\tilde{m}$ in $\mathbb{R}$, called the **push-forward**, by $\tilde{m}(A) = P(X^{-1}(A))$. By definition, this measure is invariant under $X$, and hence $$
\int_{\mathbb{R}} f d\tilde{m} = \int_{\Omega} f \circ X dP.
$$ The equality follows from the usual arguments (prove for characteristics, simple functions, then use convergence. Recall that $1_A \circ X = 1_{X^{-1}(A)}$).

Let $h$ be the density of $X$. We then have, by definition of density, that $\tilde{m}(A) = P(X^{-1}(A)) = \int_A h dm$ for any $A \in \mathcal{B}(\mathbb{R})$, where $m$ is the Lebesgue measure. By **change of variables**, we have $$
\int_{\mathbb{R}}f d\tilde{m} = \int_{\mathbb{R}} f\cdot h dm.
$$ Combining these equations, $$
\int_{\mathbb{R}} f \cdot h dm =\int_{\Omega} f \circ X dP.
$$ Taking $f=\text{Id}$ yields $$
\int_{\mathbb{R}}xh(x)dx = \int_{\Omega} X dP = E[X].
$$ Taking $f = \text{Id} \cdot \mathbf{1}_{I}$, where $I$ is some interval (for example, $(0, +\infty)$ as in your case), we have $$
\int_{I}xh(x)dx = \int_{X^{-1}}XdP,
$$ recalling again that $\mathbf{1}_A \circ X = \mathbf{1}_{X^{-1}(A)}$. Since $P(X<0)$ in your case is $0$, this last integral is actually equal to the integral over the whole space, and hence to $E[X]$, which gives your equality.
